package ast;

import environment.*;
import emitter.*;
import java.util.List;

/**
 * The Program class is used to define PASCAL Programs,
 * with procedure declaration(s) followed by a statement.
 *
 * @author Saahas Kohli
 * @version 11/19/2021
 */
public class Program
{
    private List<VariableDeclaration> vars;
    private List<ProcedureDeclaration> procDecList;
    private Statement statement;

    /**
     *
     * @param vars a list of global variable declarations
     * @param procDecList a list of Procedure declarations
     * @param statement a final Statement
     */
    public Program(List<VariableDeclaration> vars, List<ProcedureDeclaration> procDecList,
                   Statement statement)
    {
        this.vars = vars;
        this.procDecList = procDecList;
        this.statement = statement;
    }

    /**
     * Compiles a PASCAL program to MIPS.
     * @param outputFileName String denoting the name of the output file
     *                       to which MIPS code is written
     */
    public void compile(String outputFileName)
    {
        Emitter e = new Emitter(outputFileName);
        e.emit("# This represents autogenerated MIPS code that was compiled");
        e.emit("# from the PASCAL program in the given parserTest file.");
        e.emit("# @author Saahas Kohli");
        e.emit("# @version 1/18/2022");
        e.emit(".data\t# all global variables");
        for(VariableDeclaration dec: vars)
            dec.compile(e);
        e.emit(".text");
        e.emit(".globl main");
        e.emit("main:");

        statement.compile(e);

        e.emit("li $v0, 10");
        e.emit("syscall\t# normal termination");

        for(ProcedureDeclaration procDec: procDecList)
            procDec.compile(e);
    }

    /**
     * Executes the code in this PASCAL Program.
     * @param env the environment
     */
    public void exec(Environment env)
    {
        for(ProcedureDeclaration procDec: procDecList)
            procDec.exec(env);
        statement.exec(env);
    }
}
